### PR TITLE
Systemd/upstart/sysvinit support

### PR DESCRIPTION
**Pull request by tioann**

### CODE REVIEW

**Review by haomiaokuna — CHANGES_REQUESTED** [review]
So this is a deeply knotty PR that I have absolutely no idea how to make head or tails of. Which is fine. But I think some comment / documentation about what the changes are doing and why they are necessary would be useful. Maybe add a readme? I know you had to go through some contortions to get it to work properly with ubuntu 14.04. Maybe also document what specifically is needed for 14.04 vs what will work with 16.04 if we ever go to that.

**Review by sean9keenan — COMMENTED** [review]
In the same boat as H on this one^

**Comment by tioann** [comment]
I will describe the changes that I did because this actually adds several distinct changes for several reasons:

- First, the original version of pgbouncer LWRP did not work with chef 12 because it was using some form of introspection that was removed with chef 12. I replaced this with explicit variable declaration at the relevant point while working on chef 12 upgrade.
- Second, the original pgbouncer only supported upstart. Chris changed that to have it support both init.d and upstart and I made some additional changes there. However, when I switched back to chef 11.10 these would no longer work because chef did not properly report the init system used by ubuntu 14.04. There is an extra complication because both upstart and systemd support classic sysvinit scripts via a compatibility layer and pgbouncer would install both upstart and sysvinit versions with sysvinit scripts (which were erroneously picked up by chef as the right ones to use) would not really work with ubuntu because of differences in sysvinit script function libraries between redhat and ubuntu. I changed the code to ensure that only the right scripts for each system is installed.
- Third, detection of the right system to use (sysvinit, upstart, systemd) was using OS identification which is the wrong way without also taking into account the version. Furthermore, chef init system identification which is done automatically is broken for chef 11.10 (known bugs), so I implemented a robust (or so they say on stackoverflow) system that foregoes OS names and versions and looks at the init binaries to see what is in use. The script properly supports all three init systems and should be robust enough for the next couple of years.

**Review by haomiaokuna — APPROVED** [review]
The only thing I would mayyybe ask for is that lovely explanation you wrote as a answer to a review comment to be included in here as part of a readme or something. but that's a nice to have. other than that I say we're good to go.

**Pull request merged**
